### ISSUE TITLE
Data Export: Property names

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_king_pilot_dashboard#20]
Using `row_to_json` in PostgreSQL is converting all the property names to generic ones, e.g.:
`'{"f1":"Collector","f2":1145385,"f3":"Sheppard St","f4":4390,"f5":null,"f6":null,"f7":"Northbound","f8":0,"f9":1,"f10":15,"f11":1,"f12":17}'`

**Comment by rcyyu** [comment]
I also think that the format of the GeoJSON is incorrect. For example the Tileserver produces a JSON string in this format:
![image](https://user-images.githubusercontent.com/16738516/31670319-54284ac2-b325-11e7-903e-2adaded2d80b.png)
Whereas the GeoJSON produces this:
![image](https://user-images.githubusercontent.com/16738516/31670411-878ad84e-b325-11e7-9679-dfd9b41bb698.png)
The above format doesn't work at the moment.
I also believe the line ending of the file should be .json instead of .geojson.

**Comment by radumas** [comment]
Fixed by https://github.com/CityofToronto/bdit_king_pilot_dashboard/commit/7c49824c21a047226d1e9bc95649a8c145a3d0bf

**Comment by radumas** [comment]
See also https://github.com/CityofToronto/bdit_king_pilot_dashboard/commit/d116b0ea1b3ba37450b34a9a7896c64bc15eab43#diff-55b7f52f1cccf1686f23c1e5ecebd658 if you want to know how the json was created
